# Generated by Django 4.2.30 on 2026-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.CharField(max_length=50)),
                ('floor_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('timestamp', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time_display', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
